# Use official Golang image as the base image
FROM golang:1.19 AS builder

#Golang env setup
RUN mkdir -p /development/src/github.com/adarshsrinivasan/DS_S24/sql /development/src/github.com/adarshsrinivasan/DS_S24/library /development/bin
RUN export GOPATH=/development
RUN export GOROOT=/usr/local/go
RUN export PATH=$PATH:$GOPATH/bin
RUN export PATH=$PATH:$GOROOT/bin

# Set the current working directory inside the container
WORKDIR /development/src/github.com/adarshsrinivasan/DS_S24

# Copy files
COPY go.mod .
COPY go.sum .
COPY library ./library/
COPY ./Assignment4/cmd/dbapi/sql .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Build the Go app
RUN go build -o main .

# Start a new stage from scratch
FROM postgres:latest

# Install Supervisor
RUN apt-get update && apt-get install -y supervisor


# Set environment variables
## Postgres Env vars
ENV POSTGRES_USER: admin
ENV POSTGRES_PASSWORD: admin
ENV POSTGRES_DB: marketplace

## app Env vars
ENV SERVER_HOST: 0.0.0.0
ENV SERVER_PORT: 50002
ENV POSTGRES_HOST: localhost
ENV POSTGRES_PORT: 5432
ENV POSTGRES_MAX_CONN: 500

# Expose port
EXPOSE 50002

# Copy the compiled Go binary from the builder stage into this new stage
COPY --from=builder /development/src/github.com/adarshsrinivasan/DS_S24/main /app/main

# Copy Supervisor configuration file
COPY ./Assignment4/cmd/dbapi/sql/start.sh .

RUN chmod +x start.sh

# Run the Go binary
CMD ["./start.sh"]
