version: '3'

services:
  server-buyer1:
    image: adarshzededa/server-buyer:latest
    platform: "linux/amd64"
    build:
      dockerfile: ./Dockerfile-server
    restart: always
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 50001
      TRANSACTION_HOST: transaction-service
      TRANSACTION_PORT: 50004
      NODE_NAME: server-buyer1
      NOSQL_NODE_NAMES: product-db1,product-db2,product-db3,product-db4,product-db5
      NOSQL_NODE_PORTS: 50001,50002,50003,50004,50005
      SQL_NODE_NAMES: customer-db1,customer-db2,customer-db3,customer-db4,customer-db5
      SQL_NODE_PORTS: 50001,50002,50003,50004,50005
    extra_hosts:
      - "customer-db1:10.10.1.1"
      - "customer-db2:10.10.1.1"
      - "customer-db3:10.10.1.1"
      - "customer-db4:10.10.1.1"
      - "customer-db5:10.10.1.1"
      - "product-db1:10.10.1.2"
      - "product-db2:10.10.1.2"
      - "product-db3:10.10.1.2"
      - "product-db4:10.10.1.2"
      - "product-db5:10.10.1.2"
      - "transaction-service:10.10.1.3"
    network_mode: "host"

  server-buyer2:
    image: adarshzededa/server-buyer:latest
    platform: "linux/amd64"
    build:
      dockerfile: ./Dockerfile-server
    restart: always
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 50002
      TRANSACTION_HOST: transaction-service
      TRANSACTION_PORT: 50004
      NODE_NAME: server-buyer2
      NOSQL_NODE_NAMES: product-db1,product-db2,product-db3,product-db4,product-db5
      NOSQL_NODE_PORTS: 50001,50002,50003,50004,50005
      SQL_NODE_NAMES: customer-db1,customer-db2,customer-db3,customer-db4,customer-db5
      SQL_NODE_PORTS: 50001,50002,50003,50004,50005
    extra_hosts:
      - "customer-db1:10.10.1.1"
      - "customer-db2:10.10.1.1"
      - "customer-db3:10.10.1.1"
      - "customer-db4:10.10.1.1"
      - "customer-db5:10.10.1.1"
      - "product-db1:10.10.1.2"
      - "product-db2:10.10.1.2"
      - "product-db3:10.10.1.2"
      - "product-db4:10.10.1.2"
      - "product-db5:10.10.1.2"
      - "transaction-service:10.10.1.3"
    network_mode: "host"

  server-buyer3:
    image: adarshzededa/server-buyer:latest
    platform: "linux/amd64"
    build:
      dockerfile: ./Dockerfile-server
    restart: always
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 50003
      TRANSACTION_HOST: transaction-service
      TRANSACTION_PORT: 50004
      NODE_NAME: server-buyer3
      NOSQL_NODE_NAMES: product-db1,product-db2,product-db3,product-db4,product-db5
      NOSQL_NODE_PORTS: 50001,50002,50003,50004,50005
      SQL_NODE_NAMES: customer-db1,customer-db2,customer-db3,customer-db4,customer-db5
      SQL_NODE_PORTS: 50001,50002,50003,50004,50005
    extra_hosts:
      - "customer-db1:10.10.1.1"
      - "customer-db2:10.10.1.1"
      - "customer-db3:10.10.1.1"
      - "customer-db4:10.10.1.1"
      - "customer-db5:10.10.1.1"
      - "product-db1:10.10.1.2"
      - "product-db2:10.10.1.2"
      - "product-db3:10.10.1.2"
      - "product-db4:10.10.1.2"
      - "product-db5:10.10.1.2"
      - "transaction-service:10.10.1.3"
    network_mode: "host"

  server-buyer4:
    image: adarshzededa/server-buyer:latest
    platform: "linux/amd64"
    build:
      dockerfile: ./Dockerfile-server
    restart: always
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 50004
      TRANSACTION_HOST: transaction-service
      TRANSACTION_PORT: 50004
      NODE_NAME: server-buyer4
      NOSQL_NODE_NAMES: product-db1,product-db2,product-db3,product-db4,product-db5
      NOSQL_NODE_PORTS: 50001,50002,50003,50004,50005
      SQL_NODE_NAMES: customer-db1,customer-db2,customer-db3,customer-db4,customer-db5
      SQL_NODE_PORTS: 50001,50002,50003,50004,50005
    extra_hosts:
      - "customer-db1:10.10.1.1"
      - "customer-db2:10.10.1.1"
      - "customer-db3:10.10.1.1"
      - "customer-db4:10.10.1.1"
      - "customer-db5:10.10.1.1"
      - "product-db1:10.10.1.2"
      - "product-db2:10.10.1.2"
      - "product-db3:10.10.1.2"
      - "product-db4:10.10.1.2"
      - "product-db5:10.10.1.2"
      - "transaction-service:10.10.1.3"
    network_mode: "host"